name: Run Tests

on:
  push:
    branches:
      - finalize/user


# Ensure only one test workflow runs at a time for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

  # Job to test the question-service
jobs:
  test_user:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      # INSTALL PNPM
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      # SETUP NODE
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install deps
      - name: Install dependencies
        run: pnpm install
        working-directory: ./services/user-service
      
      # test
      - name: Run tests
        run: pnpm test
        working-directory: ./services/user-service

      - name: Run integration tests
        run: pnpm test tests/integration/
        working-directory: ./services/user-service
        
  test_question:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      # INSTALL PNPM
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      # SETUP NODE
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install deps
      - name: Install dependencies
        run: pnpm install
        working-directory: ./services/question-service
      
      # test
      - name: Run tests
        run: pnpm test
        working-directory: ./services/question-service

      - name: Run integration tests
        run: pnpm test tests/integration/
        working-directory: ./services/question-service
  
